"""Added user profile table

Revision ID: 4191a362d8ed
Revises: 146a2020f23a
Create Date: 2026-04-13 18:13:30.996670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4191a362d8ed'
down_revision: Union[str, Sequence[str], None] = '146a2020f23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_registrations_event_id'), 'registrations', ['event_id'], unique=False)
    op.drop_constraint(op.f('registrations_event_id_fkey'), 'registrations', type_='foreignkey')
    op.create_foreign_key(None, 'registrations', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.create_foreign_key(op.f('registrations_event_id_fkey'), 'registrations', 'events', ['event_id'], ['id'])
    op.drop_index(op.f('ix_registrations_event_id'), table_name='registrations')
    # ### end Alembic commands ###
